eureka:
  instance:
    hostname: localhost

server:
  port: 8999


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: users-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

        - id: contact-service
          uri: lb://contact-service
          predicates:
            - Path=/contact/**




eurek